language: cpp

compiler:
  - gcc

before_script: 
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..
  
install: 
  - wget https://sourceforge.net/projects/arma/files/armadillo-10.1.1.tar.xz/download
  - tar -xvf download
  - cd armadillo-10.1.1
  - cmake .
  - make
  - make install  
  - cd ..
script:
  # once CMake has done its job we just build using make as usual
  - make
